### ISSUE TITLE
update granola recipe

### ISSUE THREAD

**Issue by ljanda** [lajanda/Test#1]
what kind of recipe is this?! i need the level of detail you included when you sent along your tuna casserole recipe!!

**Comment by lajanda** [comment]
Sorry, I got distracted. I have a really good recipe and will fix that up and share it, asap. I will add another comment to this thread when it is done. I just made another huge batch of granola on Tuesday evening...

**Comment by ljanda-amplify** [comment]
you can `git commit -m "resolve #1 by adding full recipe"` to close this issue with a push when do you update the recipe! [reference doc](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)
